In [15]:
import polars as pl
import pandas as pd
import numpy as mp
import altair as alt
import pyarrow
from pyarrow import dictionary

from func.UsefulFunctions import *

This notebook is for merging the various group related data

In [16]:
groupDF = pd.read_csv("./Group Info/Query 114 - Musical Ensembles (and subclasses such as bands) + genre + type of group + inception year + country of origin + record label – Only group name is labelled.csv",low_memory=False)
groups_with_wikiDF = pd.read_csv("./Group Info/Query 18 - The Wikipedia Pages (if they have one) For All Music Ensembles.csv")
groups_with_MB_DF = pd.read_csv("./Group Info/Query 25 - Groups and their musicBrainzID.csv")
groups_with_statementsDF = pd.read_csv("./Group Info/Query 27 - Unlabelled Musical Groups and number of statements.csv")
groups_with_influencesDF = pd.read_csv("./Group Info/Query 115 - Groups and who they were influenced by.csv")

In [17]:
def addLabels(df, columnName):
    dictionary = getLabels(df[columnName].dropna().unique().tolist())
    labelLabel = columnName + "Label"
    dictionaryDF = pd.DataFrame(dictionary.items(), columns=[columnName, labelLabel])
    df = df.merge(dictionaryDF, on=columnName, how='left')

    return df

In [18]:
#Clean up each entity
groupDF[['group','genre','groupType','countryOfOrigin','recordLabel']] = groupDF[['group','genre','groupType','countryOfOrigin','recordLabel']].map(getEntityIDValue)
groupDF.inception = groupDF.inception.map(getYear)


# genre_dict = getLabels(groupDF['genre'].dropna().unique().tolist())
# genre_pdDF = pd.DataFrame(genre_dict.items(), columns=['genre','genreLabel'])
# groupDF = groupDF.merge(genre_pdDF, on='genre', how='left')
groupDF['genre'] = groupDF['genre'].where(groupDF['genre'].str.startswith('Q'), None)
groupDF = addLabels(groupDF, 'genre')
groupDF['groupType'] = groupDF['groupType'].where(groupDF['groupType'].str.startswith('Q'), None)
groupDF = addLabels(groupDF, 'groupType')
groupDF.countryOfOrigin = groupDF.countryOfOrigin.where(groupDF['countryOfOrigin'].str.startswith('Q'), None)
groupDF = addLabels(groupDF, 'countryOfOrigin')
groupDF['recordLabel'] = groupDF['recordLabel'].where(groupDF['recordLabel'].str.startswith('Q'), None)
groupDF = addLabels(groupDF, 'recordLabel')

groupDF.head(5)

The number of keys in the dictionary is 1705
This is the list of ids: {wd:Q877693 wd:Q20474 wd:Q20502 wd:Q851213 wd:Q83270 wd:Q20378 wd:Q206159 wd:Q316930 wd:Q667659 wd:Q8341 wd:Q484641 wd:Q856872 wd:Q183504 wd:Q211573 wd:Q885561 wd:Q837837 wd:Q9759 wd:Q187760 wd:Q606393 wd:Q216961 wd:Q11366 wd:Q325504 wd:Q3071 wd:Q852767 wd:Q49451 wd:Q11403 wd:Q263734 wd:Q2389651 wd:Q208494 wd:Q28146601 wd:Q438503 wd:Q253918 wd:Q487914 wd:Q1425661 wd:Q850412 wd:Q2336819 wd:Q830325 wd:Q105527 wd:Q968730 wd:Q476983 wd:Q11399 wd:Q379671 wd:Q9730 wd:Q517415 wd:Q842324 wd:Q235858 wd:Q45981 wd:Q1298934 wd:Q2525544 wd:Q132438 wd:Q217467 wd:Q484179 wd:Q56351111 wd:Q486415 wd:Q1772422 wd:Q2045695 wd:Q6010 wd:Q37073 wd:Q186472 wd:Q11365 wd:Q1046768 wd:Q1391336 wd:Q822914 wd:Q1786724 wd:Q217191 wd:Q38848 wd:Q211756 wd:Q131578 wd:Q202930 wd:Q436016 wd:Q997481 wd:Q186170 wd:Q193355 wd:Q83440 wd:Q7749 wd:Q2265866 wd:Q372103 wd:Q208239 wd:Q959583 wd:Q617240 wd:Q483251 wd:Q483352 wd:Q9778 wd:Q753520 wd:Q76092 wd:Q485395 wd:Q10922 wd:Q854451 wd:Q170611 wd:Q241662 wd:Q910606 wd:Q484344 wd:Q719927 wd:Q918542 wd:Q57143 wd:Q164444 wd:Q54365 wd:Q183862 wd:Q9794 wd:Q3046632 wd:Q2624785 wd:Q10926 wd:Q598929 wd:Q3930216 wd:Q1641839 wd:Q58339 wd:Q131272 wd:Q38656 wd:Q264289 wd:Q11787389 wd:Q1374731 wd:Q2281409 wd:Q213665 wd:Q43343 wd:Q438476 wd:Q2572585 wd:Q1190565 wd:Q379033 wd:Q211723 wd:Q2296495 wd:Q1133657 wd:Q783097 wd:Q627906 wd:Q11401 wd:Q213714 wd:Q3827483 wd:Q56580 wd:Q546359 wd:Q255406 wd:Q9764 wd:Q504635 wd:Q2089511 wd:Q178145 wd:Q966564 wd:Q213121 wd:Q876171 wd:Q1621467 wd:Q26473 wd:Q3231749 wd:Q188450 wd:Q2118402 wd:Q972634 wd:Q685884 wd:Q189045 wd:Q3397882 wd:Q1190485 wd:Q739138 wd:Q205049 wd:Q1317816 wd:Q1433547 wd:Q39052604 wd:Q3322869 wd:Q1457545 wd:Q2035976 wd:Q533914 wd:Q135637 wd:Q377910 wd:Q429264 wd:Q828305 wd:Q542703 wd:Q203720 wd:Q817138 wd:Q641357 wd:Q284543 wd:Q170435 wd:Q320592 wd:Q899116 wd:Q1795903 wd:Q846784 wd:Q655514 wd:Q27190 wd:Q8361 wd:Q1990122 wd:Q622871 wd:Q209137 wd:Q188539 wd:Q1192110 wd:Q7308175 wd:Q972424 wd:Q3328660 wd:Q16056349 wd:Q1899347 wd:Q1062400 wd:Q547137 wd:Q1785028 wd:Q4078107 wd:Q41343 wd:Q185298 wd:Q775614 wd:Q236913 wd:Q487965 wd:Q858579 wd:Q203775 wd:Q131425 wd:Q744417 wd:Q597240 wd:Q1273641 wd:Q747717 wd:Q720959 wd:Q1929352 wd:Q613408 wd:Q15957030 wd:Q828243 wd:Q7067688 wd:Q835891 wd:Q205560 wd:Q193207 wd:Q251192 wd:Q212688 wd:Q282131 wd:Q124312240 wd:Q25094849 wd:Q784310 wd:Q601235 wd:Q2332751 wd:Q1650296 wd:Q726239 wd:Q28444186 wd:Q650316 wd:Q181861 wd:Q4045538 wd:Q113493820 wd:Q1455292 wd:Q602646 wd:Q274401 wd:Q325397 wd:Q1139136 wd:Q753679 wd:Q2517263 wd:Q2187392 wd:Q828181 wd:Q823080 wd:Q936942 wd:Q2416307 wd:Q188994 wd:Q646679 wd:Q970409 wd:Q217597 wd:Q967654 wd:Q446241 wd:Q341395 wd:Q1166197 wd:Q236932 wd:Q15629158 wd:Q180268 wd:Q55296418 wd:Q1640319 wd:Q3840596 wd:Q969663 wd:Q221772 wd:Q13634037 wd:Q383615 wd:Q2076779 wd:Q42201 wd:Q2324411 wd:Q19678100 wd:Q107572242 wd:Q370778 wd:Q1431327 wd:Q460674 wd:Q1206160 wd:Q641318 wd:Q3868787 wd:Q286080 wd:Q944465 wd:Q1373485 wd:Q378988 wd:Q1435485 wd:Q1403744 wd:Q428656 wd:Q108250543 wd:Q675553 wd:Q76825003 wd:Q185162 wd:Q481900 wd:Q3328599 wd:Q188534 wd:Q7439349 wd:Q28949059 wd:Q2456210 wd:Q898709 wd:Q5151495 wd:Q213149 wd:Q3328774 wd:Q840065 wd:Q2101610 wd:Q1952679 wd:Q3724735 wd:Q431415 wd:Q756956 wd:Q16241990 wd:Q2407862 wd:Q2268922 wd:Q1414130 wd:Q3486097 wd:Q1076092 wd:Q874038 wd:Q2599472 wd:Q616679 wd:Q1890098 wd:Q1147692 wd:Q1051575 wd:Q39052425 wd:Q1064810 wd:Q475221 wd:Q1166218 wd:Q546264 wd:Q1507298 wd:Q341364 wd:Q21662779 wd:Q1378776 wd:Q14390274 wd:Q465978 wd:Q11363 wd:Q2532560 wd:Q703778 wd:Q592060 wd:Q105636940 wd:Q612024 wd:Q1338153 wd:Q253137 wd:Q2532274 wd:Q2746731 wd:Q1995980 wd:Q383982 wd:Q183016 wd:Q2461933 wd:Q106581777 wd:Q2608506 wd:Q5724040 wd:Q1983116 wd:Q868855 wd:Q4390945 wd:Q1432934 wd:Q373342 wd:Q492264 wd:Q213572 wd:Q1027999 wd:Q2260696 wd:Q2302695 wd:Q1136765 wd:Q220830 wd:Q915152 wd:Q1884689 wd:Q1181308 wd:Q5069525 wd:Q1643549 wd:Q3437821 wd:Q1051843 wd:Q663519 wd:Q1784032 wd:Q19938910 wd:Q1164252 wd:Q659599 wd:Q606089 wd:Q474027 wd:Q602498 wd:Q1936659 wd:Q727781 wd:Q1500364 wd:Q2997058 wd:Q110874774 wd:Q1065742 wd:Q965635 wd:Q1928583 wd:Q2266376 wd:Q2087267 wd:Q1132152 wd:Q592330 wd:Q46046 wd:Q30587784 wd:Q4490718 wd:Q65937017 wd:Q106621114 wd:Q17723 wd:Q3437841 wd:Q1695023 wd:Q1253172 wd:Q932477 wd:Q1268283 wd:Q1151260 wd:Q825769 wd:Q7118426 wd:Q1430587 wd:Q805044 wd:Q1076513 wd:Q371745 wd:Q11700058 wd:Q3482281 wd:Q598593 wd:Q2994332 wd:Q823560 wd:Q1089050 wd:Q454071 wd:Q16562829 wd:Q24383 wd:Q861823 wd:Q4428744 wd:Q9162904 wd:Q272167}

,group,groupLabel,genre,groupType,inception,countryOfOrigin,recordLabel,genreLabel,groupTypeLabel,countryOfOriginLabel,recordLabelLabel
0,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records
1,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q1759336,rap rock,musical group,United States,Revelation Records
2,Q72349,Krewella,Q20474,Q14073567,2010.0,Q30,Q183387,dubstep,sibling duo,United States,Columbia Records
3,Q72349,Krewella,Q20474,Q14073567,2010.0,Q30,Q10398667,dubstep,sibling duo,United States,Monstercat
4,Q72349,Krewella,Q20502,Q14073567,2010.0,Q30,Q183387,house music,sibling duo,United States,Columbia Records

In [19]:
#This fixes any errors that were in the dataset by making sure the influenced by influence is an actual Q entity
groups_with_influencesDF[['group','influencedby']] = groups_with_influencesDF[['group','influencedby']].map(getEntityIDValue)
groups_with_influencesDF = groups_with_influencesDF[groups_with_influencesDF.influencedby.str.startswith('Q')]

groupDF = groupDF.merge(groups_with_influencesDF[['group','influencedby','influencedbyLabel']], how='left', on='group')


groupDF.head()

,group,groupLabel,genre,groupType,inception,countryOfOrigin,recordLabel,genreLabel,groupTypeLabel,countryOfOriginLabel,recordLabelLabel,influencedby,influencedbyLabel
0,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q924413,24-7 Spyz
1,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q392,Bob Dylan
2,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q10708,Red Hot Chili Peppers
3,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q622947,Jane's Addiction
4,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q464476,Black Flag

In [20]:
display(groups_with_MB_DF[groups_with_MB_DF['musicBrainzID'].str.contains("http")])
individualWithIssue = groups_with_MB_DF[groups_with_MB_DF['musicBrainzID'].str.contains("http")]
individualWithIssue.to_csv("./missingValuesStore/groupEntityWithFormattingIssueInTheirMusicBrainz.csv", index=False)
groups_with_MB_DF[['group','musicBrainzID']] = groups_with_MB_DF[['group','musicBrainzID']].map(getEntityIDValue)
display(groups_with_MB_DF[['group','musicBrainzID']])
display(groups_with_MB_DF[groups_with_MB_DF.group == "Q140450482"])
groupDF = groupDF.merge(groups_with_MB_DF[['group','musicBrainzID']], how='left', on='group')

groupDF.head()

,group,groupLabel,musicBrainzID
72277,http://www.wikidata.org/entity/Q140450482,Q140450482,https://musicbrainz.org/artist/632cbe4d-5a1c-4...

            group                         musicBrainzID
0          Q74160  7ba22880-978f-4e4c-849a-3baf167fc9c0
1         Q114543  e883133b-1b8e-4bfd-bc6f-45e1bf1584f0
2         Q116411  5f549372-3e08-42aa-ad67-0d3c60e1b86d
3         Q113484  0136756e-c79d-4d76-af7a-9471f0cca4e6
4         Q114651  3cc3942d-bbfc-446d-a8f4-f0e1e238ca86
...           ...                                   ...
77733  Q118294981  501997ee-e3c0-4d36-8bef-ccfc1c5d1635
77734  Q121603439  8d0ea88f-2820-4b61-a780-4406c9fb3e99
77735  Q115490619  6a052517-27f9-40bd-aab5-10f7f6ada4fa
77736  Q116368208  66ea2957-9423-46d0-b871-ef4afe5c1566
77737  Q115526174  f96285cb-fdde-4529-9cd3-d253d49a11bc

[77738 rows x 2 columns]

            group  groupLabel                         musicBrainzID
72277  Q140450482  Q140450482  632cbe4d-5a1c-4e75-8276-e2e4e9faaa61

,group,groupLabel,genre,groupType,inception,countryOfOrigin,recordLabel,genreLabel,groupTypeLabel,countryOfOriginLabel,recordLabelLabel,influencedby,influencedbyLabel,musicBrainzID
0,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q924413,24-7 Spyz,3798b104-01cb-484c-a3b0-56adc6399b80
1,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q392,Bob Dylan,3798b104-01cb-484c-a3b0-56adc6399b80
2,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q10708,Red Hot Chili Peppers,3798b104-01cb-484c-a3b0-56adc6399b80
3,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q622947,Jane's Addiction,3798b104-01cb-484c-a3b0-56adc6399b80
4,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q464476,Black Flag,3798b104-01cb-484c-a3b0-56adc6399b80

In [21]:
groups_with_wikiDF.group = groups_with_wikiDF.group.map(getEntityIDValue)
#This ensure it is a valid english wikipedia link
groups_with_wikiDF = groups_with_wikiDF[groups_with_wikiDF.article.str.contains("en.wikipedia")]
display(groups_with_wikiDF)
groups_with_statementsDF.group = groups_with_statementsDF.group.map(getEntityIDValue)

groupDF = groupDF.merge(groups_with_wikiDF[['group','article']], how='left', on='group')
groupDF = groupDF.merge(groups_with_statementsDF, how='left', on='group')

groupDF.head()

,group,groupLabel,page_titleEN,article
0,Q261,Linkin Park,Linkin Park,https://en.wikipedia.org/wiki/Linkin_Park
1,Q32645,Die Ärzte,Die Ärzte,https://en.wikipedia.org/wiki/Die_%C3%84rzte
2,Q32542,The Magnetic Fields,The Magnetic Fields,https://en.wikipedia.org/wiki/The_Magnetic_Fields
3,Q32543,Test Icicles,Test Icicles,https://en.wikipedia.org/wiki/Test_Icicles
4,Q32591,Crooked Still,Crooked Still,https://en.wikipedia.org/wiki/Crooked_Still
...,...,...,...,...
50443,Q112795795,18th & Addison,18th & Addison,https://en.wikipedia.org/wiki/18th_%26_Addison
50444,Q113133049,123 Andrés,123 Andrés,https://en.wikipedia.org/wiki/123_Andr%C3%A9s
50445,Q113022702,LF System,LF System,https://en.wikipedia.org/wiki/LF_System
50446,Q113022885,Frontperson,Frontperson,https://en.wikipedia.org/wiki/Frontperson
50447,Q112341328,Shwi no Mtekhala,Shwi no Mtekhala,https://en.wikipedia.org/wiki/Shwi_no_Mtekhala

,group,groupLabel,genre,groupType,inception,countryOfOrigin,recordLabel,genreLabel,groupTypeLabel,countryOfOriginLabel,recordLabelLabel,influencedby,influencedbyLabel,musicBrainzID,article,statementCount
0,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q924413,24-7 Spyz,3798b104-01cb-484c-a3b0-56adc6399b80,https://en.wikipedia.org/wiki/Rage_Against_the...,125.0
1,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q392,Bob Dylan,3798b104-01cb-484c-a3b0-56adc6399b80,https://en.wikipedia.org/wiki/Rage_Against_the...,125.0
2,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q10708,Red Hot Chili Peppers,3798b104-01cb-484c-a3b0-56adc6399b80,https://en.wikipedia.org/wiki/Rage_Against_the...,125.0
3,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q622947,Jane's Addiction,3798b104-01cb-484c-a3b0-56adc6399b80,https://en.wikipedia.org/wiki/Rage_Against_the...,125.0
4,Q72092,Rage Against the Machine,Q877693,Q215380,2001.0,Q30,Q216364,rap rock,musical group,United States,Epic Records,Q464476,Black Flag,3798b104-01cb-484c-a3b0-56adc6399b80,https://en.wikipedia.org/wiki/Rage_Against_the...,125.0

In [22]:
groupDF[groupDF['genreLabel'].str.contains("wikidata")]

Empty DataFrame
Columns: [group, groupLabel, genre, groupType, inception, countryOfOrigin, recordLabel, genreLabel, groupTypeLabel, countryOfOriginLabel, recordLabelLabel, influencedby, influencedbyLabel, musicBrainzID, article, statementCount]
Index: []

In [23]:
groupDF.dtypes

group                       str
groupLabel                  str
genre                       str
groupType                   str
inception               float64
countryOfOrigin             str
recordLabel                 str
genreLabel                  str
groupTypeLabel              str
countryOfOriginLabel        str
recordLabelLabel            str
influencedby                str
influencedbyLabel           str
musicBrainzID               str
article                     str
statementCount          float64
dtype: object

In [24]:
#de-duplicate the data and then save it as a parquet for cleaning later

groupDF.drop_duplicates(inplace=True)
groupDF.to_parquet("./Data/pipelinedGroupsWikidata.parquet")